packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  prisma: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - turbo@2.11.3
  - '@orpc/client@1.15.4'
  - '@orpc/contract@1.15.4'
  - '@orpc/shared@1.15.4'
  - '@orpc/standard-server-fetch@1.15.4'
  - '@orpc/standard-server-peer@1.15.4'
  - '@orpc/standard-server@1.15.4'
  - '@nestjs/common@12.1.0'
  - '@nestjs/core@12.1.0'
  - '@nestjs/platform-express@12.1.0'
  - '@orpc/interop@1.15.4'
  - '@orpc/nest@1.15.4'
  - '@orpc/openapi-client@1.15.4'
  - '@orpc/openapi@1.15.4'
  - '@orpc/server@1.15.4'
  - '@orpc/standard-server-aws-lambda@1.15.4'
  - '@orpc/standard-server-fastify@1.15.4'
  - '@orpc/standard-server-node@1.15.4'
  - '@tanstack/react-router@1.170.39'
  - '@orpc/tanstack-query@1.15.4'
