packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  prisma: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - turbo@2.11.3
  - '@orpc/client@1.15.4'
  - '@orpc/contract@1.15.4'
  - '@orpc/shared@1.15.4'
  - '@orpc/standard-server-fetch@1.15.4'
  - '@orpc/standard-server-peer@1.15.4'
  - '@orpc/standard-server@1.15.4'
  - '@nestjs/common@12.1.0'
  - '@nestjs/core@12.1.0'
  - '@nestjs/platform-express@12.1.0'
